In [1]:
from env import *

@njit
def botAnn(state, tempFile, perFile):
    validActions = getValidActions(state)
    if (validActions[5:20]==1).any():
        a = np.where(validActions[5:20]==1)[0] + 5
        idx = np.random.randint(0, len(a))
        return a[idx], tempFile, perFile
    
    if (validActions[0:5]==1).any():
        a = np.where(validActions[0:5]==1)[0]
        idx = np.random.randint(0, len(a))
        return a[idx], tempFile, perFile
    
    a = np.where(validActions==1)[0]
    idx = np.random.randint(0, len(a))
    return a[idx], tempFile, perFile


@njit
def botAnn1(state, tempFile, perFile):
    validActions = getValidActions(state)
    if (validActions[5:20]==1).any():
        a = np.where(validActions[5:20]==1)[0] + 5
        idx = -1
        return a[idx], tempFile, perFile
    
    if (validActions[0:5]==1).any():
        a = np.where(validActions[0:5]==1)[0]
        idx = np.random.randint(0, len(a))
        return a[idx], tempFile, perFile
    
    a = np.where(validActions==1)[0]
    idx = 0
    return a[idx], tempFile, perFile

In [2]:
perFile = List()
perFile.append(np.array([[0.]]))

numbaMain(botAnn, numbaRandomBot, numbaRandomBot, numbaRandomBot, 10000, perFile)

(array([9741,   91,   82,   86,    0], dtype=int64),
 ListType[array(float64, 2d, C)]([[[0.]], ...]))

In [3]:
perFile = List()
perFile.append(np.array([[0.]]))

numbaMain(numbaRandomBot, botAnn1, numbaRandomBot, numbaRandomBot, 10000, perFile)

(array([ 125, 9680,  102,   93,    0], dtype=int64),
 ListType[array(float64, 2d, C)]([[[0.]], ...]))

In [4]:
perFile = List()
perFile.append(np.array([[0.]]))

numbaMain(botAnn, botAnn1, numbaRandomBot, numbaRandomBot, 10000, perFile)

(array([4663, 5310,   16,   11,    0], dtype=int64),
 ListType[array(float64, 2d, C)]([[[0.]], ...]))